# Generated by Django 5.2.8 on 2025-12-04 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_course_instructor'),
        ('instructors', '0002_instructor_course_alter_instructor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
