# Generated by Django 5.2.8 on 2025-12-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_alter_instructor_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='instructors_image/'),
        ),
    ]
