# Generated by Django 5.2.8 on 2025-12-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_alter_instructor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
