# Generated by Django 5.2.8 on 2025-11-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='lesson/icon')),
                ('video', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('topic', models.CharField(max_length=120)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
