# Generated by Django 5.2.8 on 2025-11-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_curriculum_alter_lesson_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='curriculum',
        ),
    ]
