# Generated by Django 5.2.8 on 2025-11-30 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_lesson_options_rename_name_lesson_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculum'),
        ),
    ]
