# Generated by Django 5.2.8 on 2025-11-30 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_curriculum'),
        ('curriculum', '0004_alter_lesson_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
