# Generated by Django 5.2.8 on 2025-11-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_remove_lesson_curriculum_lesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duretion',
            field=models.FloatField(default=0),
        ),
    ]
