# Generated by Django 5.2.8 on 2025-11-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_lesson_duretion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='duretion',
            new_name='duration',
        ),
    ]
