# Generated by Django 5.2.8 on 2025-12-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='icon',
        ),
    ]
