# Generated by Django 5.2.8 on 2025-11-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='courses_images/image/')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('total_students', models.IntegerField()),
                ('total_lessons', models.IntegerField()),
                ('total_hours', models.IntegerField()),
                ('instructor_name', models.CharField(max_length=120)),
                ('instructor_avatar', models.ImageField(upload_to='courses_images/instructor_avatar/')),
                ('category', models.CharField(max_length=120)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
