# Generated by Django 5.2.8 on 2025-11-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='instructor_avatar',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='instructor_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses', to='instructors.instructor'),
        ),
    ]
