# Generated by Django 5.2.8 on 2025-11-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_instructor_avatar_and_more'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='instructors',
        ),
        migrations.AddField(
            model_name='courses',
            name='Instructors',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
        ),
    ]
