# Generated by Django 5.2.8 on 2025-11-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courses_instructors_courses_instructors'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='Instructors',
            new_name='Instructor',
        ),
        migrations.AddField(
            model_name='courses',
            name='curriculum',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='courses',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
