# Generated by Django 5.2.8 on 2025-11-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_instructors_courses_instructor_and_more'),
        ('curriculum', '0003_alter_lesson_options_rename_name_lesson_curriculum'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
