# Generated by Django 5.2.8 on 2025-11-30 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_courses_course'),
        ('curriculum', '0004_alter_lesson_curriculum'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Instructor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson'),
        ),
    ]
