# Generated by Django 5.2.8 on 2025-11-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_instructor_alter_course_curriculum'),
        ('curriculum', '0004_alter_lesson_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ManyToManyField(blank=True, to='curriculum.lesson'),
        ),
    ]
