# Generated by Django 5.2.8 on 2025-11-30 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_curriculum_course_curriculum'),
        ('curriculum', '0004_alter_lesson_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculum'),
            preserve_default=False,
        ),
    ]
