# Generated by Django 5.2.8 on 2025-11-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_curriculum_course_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
    ]
