# Generated by Django 5.2.8 on 2025-11-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_curriculum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Instructor',
            new_name='instructor',
        ),
    ]
