# Generated by Django 5.2.8 on 2025-11-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_instructor_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
