# Generated by Django 5.2.8 on 2025-12-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
